apiVersion: v1
kind: Pod
metadata:
  name: minikubesample1
spec:
  containers:
    - image: docker.io/mhmreza/minikubesample1
      name: minikubesample1
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 8080